
import React, { Component } from 'react'
import { Text, View, StyleSheet, TouchableOpacity, Button, Image, ScrollView } from 'react-native'

export class home extends Component {
    render() {
        return (
            <View  style={{backgroundColor:"black"}}>

                <View style={styles.header}>
                    <TouchableOpacity style={styles.hamburger} onPress={() => this.props.navigation.toggleDrawer()}>
                        <View style={styles.hamburgerOdd} ></View>
                        <View style={styles.hamburgerEven} ></View>
                        <View style={styles.hamburgerOdd} ></View>
                        <View style={styles.hamburgerEvenMid} ></View>
                        <View style={styles.hamburgerOdd} ></View>
                        <View style={styles.hamburgerEven} ></View>
                        <View style={styles.hamburgerOdd} ></View>
                    </TouchableOpacity >
                    <View style={styles.logoMain}>
                        <Text style={{ color: '#fff', fontFamily: '"Times New Roman", Times, serif', fontSize: 20, paddingLeft: 50 }}>Lion-Hearted Martyrs</Text>

                    </View>


                </View>
                <ScrollView>

                    <View style={{backgroundColor:"black"}}>
                        <Image style={styles.aboutimage} source={require('../assets/main.jpg')} />
                    </View>
                    <View style={{backgroundColor:"black"}}>

                        <Text style={styles.a2}>
                            The brave soldiers of Central Armed Forces fight a daily battle to safeguard India’s external and internal security. Protecting the borders in the west with Pakistan and in the north and east with China, and facing the threats generated by the militants in Jammu and Kashmir. Insurgency in the north east and Maoist extremists in central and east India, to keep us safe. One soldier loses his/her life every fourth day and one is permanently incapacitated. This is our homage to the bravehearts and an effort to provide support to their families. General public can visit the application and the website LION-HEARTED MARTYRS and make a contribution to support the families of the jawans who died in the line of duty. the main objective of the portal is to enable the public to help the families of soldiers by donating money online directly to the individual braveheart’s account or to LION-HEARTED MARTYRS
                </Text>

                    </View>
                    <View style={{ height: 80 ,  backgroundColor:"black"}}></View>
                </ScrollView>
            </View>
        )
    }
}


const styles = StyleSheet.create({
    logoText: {
        marginRight: 10,
        //   width:"75%",
        color: "#FFF",
        textAlign: 'right',
        flex: 10,
        fontFamily: 'Montserrat-Bold',
        fontSize: 18,
    },
    header: {
        height: 40,
        marginBottom: 5,
        marginTop: 10,
        // backgroundColor:"#FFF",
        flexDirection: 'row',
        alignItems: 'center',

         
borderWidth: 1,
borderRadius: 4,
borderColor: '#ddd',
borderBottomWidth: 3,
shadowColor: 'rgb(99, 97, 97)',
shadowOffset: { width: 20, height: 20 },
shadowOpacity: 1,
shadowRadius: 50,
elevation: 10,
marginLeft: 10,
marginRight: 10,
marginTop: 10,
    },
    logoMain: {
        flexDirection: 'row',
        flex: 12,
        marginRight: 15,
        // backgroundColor:'#FFF'
    },
    hamburger: {
        // width:"25%",
        width:"25%",
      
        flex: 1,
        color: '#FFF',
        margin: 5,
        marginLeft: 15,
        marginRight: 10,
        flexDirection: 'column',
        justifyContent: 'center'
        // right:10
    },
    hamburgerOdd: {
        flex: 8
    },
    hamburgerEven: {
        flex: 8,
        backgroundColor:  '#fff'
    },
    hamburgerEvenMid: {
     
        flex: 5,
        // marginLeft: '',
        backgroundColor:  '#fff'
    },

    a2: {
        fontFamily: "../assets/fonts/dream_unicorn",
        fontSize: 15,
        color: "white",
        paddingTop: 0,
        textAlign: "justify",

    },

    aboutimage: {
        height: 700,
        width: "100%"
    },
})

export default home